repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.9.2
    hooks:
      - id: isort
        args:
          - api cli langoo ml
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          - api cli langoo ml
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    - id: black
      language_version: python3.8
      args:
        - --exclude=/(\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|_build|buck-out|data|build|dist)/
        - --target-version=py38